# -*- mode: python ; coding: utf-8 -*-
# LocalRPA - 画像マッチ特化型ローカルRPAツール
# PyInstaller spec file (onefile mode)

block_cipher = None

a = Analysis(
    ['src/main.py'],
    pathex=[SPECPATH],
    binaries=[],
    datas=[],
    hiddenimports=[
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'PySide6.QtSvg',
        'cv2',
        'numpy',
        'pyautogui',
        'pyscreeze',
        'PIL',
        'PIL.Image',
        'win32api',
        'win32con',
        'win32gui',
        'src',
        'src.core',
        'src.core.context',
        'src.core.action_base',
        'src.core.dispatcher',
        'src.core.engine',
        'src.actions',
        'src.actions.image_actions',
        'src.actions.mouse_actions',
        'src.actions.keyboard_actions',
        'src.actions.wait_actions',
        'src.actions.variable_actions',
        'src.actions.condition_actions',
        'src.actions.screen_actions',
        'src.gui',
        'src.gui.main_window',
        'src.gui.flow_editor',
        'src.gui.node_widget',
        'src.gui.action_panel',
        'src.gui.settings_panel',
        'src.gui.log_panel',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='LocalRPA',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
